FROM docker.elastic.co/wolfi/python:3.11-dev@sha256:52a486eb808cc3581623b3a064ae7c68e64391cf7da20155eab10aa8930543c7
USER root
COPY . /app
WORKDIR /app
RUN make clean install
RUN ln -s .venv/bin /app/bin
ENTRYPOINT []
